const newsData = [
    {
        "id": 1,
        "category": "local",
        "title": "세종시교육청 학교회계 투명성과 효율성 강화 위한 점검 제도 도입",
        "date": "2026.02.13",
        "oneLine": "세종시교육청 학교회계 투명성과 효율성 강화 위한 점검 제도 도입",
        "content": "세종시교육청 학교회계 투명성과 효율성 강화 위한 점검 제도 도입  매일일보",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiZEFVX3lxTFBQWE92TE9fR25qSDFBWS1IYTBsbHBTUWl1ZnFRRHQ1VWtJbzJ6eXBIQngzdVRrbkR3NEZZdnU3MllpTFQzbEJ5eGlOU1IxdHo4QjltTmFOdUs2azJYZ0lubVpRUXg?oc=5"
    },
    {
        "id": 2,
        "category": "local",
        "title": "[위클리오늘] 경기도교육청, ‘2026 학교평가 운영 안내서’ 3종 발간",
        "date": "2026.02.13",
        "oneLine": "[위클리오늘] 경기도교육청, ‘2026 학교평가 운영 안내서’ 3종 발간",
        "content": "[위클리오늘] 경기도교육청, ‘2026 학교평가 운영 안내서’ 3종 발간  위클리오늘",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMibkFVX3lxTE1ocGE1NE5kdXFfWlpzX2kyeDUtUTVpREFfODJQckRxMWpyYXdLRTNNTlRLZHBsUHl5WURHOFExenVHVUJZdXpfdVlvcGRoRWdXQ0RZSjVuYWdOd0FUb243cWJvTWdKTkhMZUxOaUtB?oc=5"
    },
    {
        "id": 3,
        "category": "trend",
        "title": "[AI 뉴스] AI가 해커의 생산성 도구로…구글, 2025년 4분기 AI 위협 보고서 공개",
        "date": "2026.02.13",
        "oneLine": "[AI 뉴스] AI가 해커의 생산성 도구로…구글, 2025년 4분기 AI 위협 보고서 공개",
        "content": "[AI 뉴스] AI가 해커의 생산성 도구로…구글, 2025년 4분기 AI 위협 보고서 공개  아웃소싱타임스",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMickFVX3lxTE00WFZfRE81ZmxiUDJqTGdfQmdnWnNBTzJMdmdkUmlJWk9rUVVnMVNycmxRMWpwRVJhdzcxNGN1MEJhQjZ4cDFhUjBNTXhxYXJBeGJJQ0hoeUN0SzZxVk9Rb0FiaVdwMW96UVlmZndELUlZQQ?oc=5"
    },
    {
        "id": 4,
        "category": "local",
        "title": "경기도교육청, 학교 자율운영 촉진하는 ‘선순환 학교평가 체제’ 본격 가동",
        "date": "2026.02.13",
        "oneLine": "경기도교육청, 학교 자율운영 촉진하는 ‘선순환 학교평가 체제’ 본격 가동",
        "content": "경기도교육청, 학교 자율운영 촉진하는 ‘선순환 학교평가 체제’ 본격 가동  일간경기",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTE9zLUl3dzdHZWU3QldjV2xsQWJZTjNHVV81Umdic2dnSWNvRkIyb29fdnFnRk9EUEJtNld0c0ZHRk9lQzNUcGFuNXl6cW5qdVZjQVRNdlAxZnpyZkd5V0w2eU1PakxFQzY5?oc=5"
    },
    {
        "id": 5,
        "category": "policy",
        "title": "시흥시, '온동네 초등돌봄' 전국 최초 민관학 협력 모델로 주도 나서",
        "date": "2026.02.13",
        "oneLine": "시흥시, '온동네 초등돌봄' 전국 최초 민관학 협력 모델로 주도 나서",
        "content": "시흥시, '온동네 초등돌봄' 전국 최초 민관학 협력 모델로 주도 나서  경기일보",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE1teFoxMHh3QXdPc2gtWDR6X2tKS3plbElDeXd0RF9rd0lHLXV6VEVEd2V2UEJ3M1ZURm96VWhCYlBUb29LN3l3MWQwd2dmZmVIN3g1WEZXbWxHc2s?oc=5"
    },
    {
        "id": 6,
        "category": "edutech",
        "title": "AI가 만든 '웅진스마트올 레인저스'",
        "date": "2026.02.13",
        "oneLine": "AI가 만든 '웅진스마트올 레인저스'",
        "content": "AI가 만든 '웅진스마트올 레인저스'  fnnews.com",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE05YTFwZTZCanFVWDRsLXBrUF9xYUt1TnA3Y3JXa2ZVZlBicWpZX2k2WHRvS0hHNWhhelk4dXF2M2hzTkp5cWYySVNRWmhlY0ttQzV2T1NJekNZQdIBXkFVX3lxTFA3WWY4Y3FtYjB6ZkJGMVR2SUgzOHlMRnR1VWZleGJTeGxpXzMzVS1DZFdON250UUYwUzZidS05dDhPckk3QmFOckJCVjRpQnlFNm85cFZMMm9VNERObHc?oc=5"
    },
    {
        "id": 7,
        "category": "edutech",
        "title": "웅진씽크빅, 생성형 AI로 만든 ‘웅진스마트올 레인저스’ 광고 공개",
        "date": "2026.02.13",
        "oneLine": "웅진씽크빅, 생성형 AI로 만든 ‘웅진스마트올 레인저스’ 광고 공개",
        "content": "웅진씽크빅, 생성형 AI로 만든 ‘웅진스마트올 레인저스’ 광고 공개  뉴스클레임",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE90Wi1KdTIwVEYxMEJtQ2N2YnhWYmNzaloxVEpMOE4zRFVRdGZNSGs2bUNNR3JyUmFnNThORXRrS05aNl9tWWdJZnlSRU5qT0g4aXVRWDVtNFRsRndVRWVlV2tiT3BuODRGN0c3TmdCT1jSAXRBVV95cUxQdHduYlBCMElNbWxUeGxXbERERUJXQWhhVFhLcGxpWEg0QnpDSGxMWkVWaVlSWnVsN29EREhfYVN3WFA4a2RDT1J3ODFwUnY4ZzhVd3k0NzZuSGd4UEdQRzlGSzlwRThFNnhhVkhBV3MtNl95aw?oc=5"
    },
    {
        "id": 8,
        "category": "trend",
        "title": "\"18개월 내 사무직 자동화\" VS \"위기론은 과장\"… AI 미래, 빅테크 수장들 동상이몽",
        "date": "2026.02.13",
        "oneLine": "\"18개월 내 사무직 자동화\" VS \"위기론은 과장\"… AI 미래, 빅테크 수장들 동상이몽",
        "content": "\"18개월 내 사무직 자동화\" VS \"위기론은 과장\"… AI 미래, 빅테크 수장들 동상이몽  kmjournal.net",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiakFVX3lxTE9GQi0zQkJnV1BGTF9XZWxleEptMDYyR1h2emJTSDNvYmo0dWhPMmVXQ3ZIMVF2eWdTWTR4RFJ3M1ZqbUt4aW1aSWJJb3lBR2JJOF9mMV84cGdhcHZlaFdJNWpucXNqdjRmS3c?oc=5"
    },
    {
        "id": 9,
        "category": "edutech",
        "title": "도교육청, ‘AI+X’ 융합 교육 가속화…직업계고 교원 200명 실무 연수",
        "date": "2026.02.13",
        "oneLine": "도교육청, ‘AI+X’ 융합 교육 가속화…직업계고 교원 200명 실무 연수",
        "content": "도교육청, ‘AI+X’ 융합 교육 가속화…직업계고 교원 200명 실무 연수  화성신문",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiQkFVX3lxTFBwY2syVUV2RlE5RVE4WE0xZHNMWjB5VWJuODBDSmZ3WVQ5WHAzX09pVzdwVkpsbFV2LUIxNjJZcFNIZw?oc=5"
    },
    {
        "id": 10,
        "category": "edutech",
        "title": "경기도교육청, 직업계고 교원 200명 대상 'AI+X 교육과정' 연수…실무형 인재 양성 강화",
        "date": "2026.02.13",
        "oneLine": "경기도교육청, 직업계고 교원 200명 대상 'AI+X 교육과정' 연수…실무형 인재 양성 강화",
        "content": "경기도교육청, 직업계고 교원 200명 대상 'AI+X 교육과정' 연수…실무형 인재 양성 강화  네이트",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTFBCdGZfR1dsTmtoRXZ3eGhnWDJPaVBUY3hkak5ZSzd0c2k5R2lfRTl1NXJyT0lNQUpiSHNfR3F6Nll1aUczVi16c2NoR0YwOHNYc0JN?oc=5"
    },
    {
        "id": 11,
        "category": "trend",
        "title": "AI 해킹 현실화…구글 제미나이, 사이버 공격자들의 ‘표적’",
        "date": "2026.02.13",
        "oneLine": "AI 해킹 현실화…구글 제미나이, 사이버 공격자들의 ‘표적’",
        "content": "AI 해킹 현실화…구글 제미나이, 사이버 공격자들의 ‘표적’  산경투데이",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFB1WmZSTW5jUGxseFpEb09JMXptR2tLWkxEdXhVQS10SDBPVWtzVVk3RUwzVkEtM0F2TkdoRGQ3QXdIZmp2c0huY3BnRDdoV1RiQnpBVFExTFA0QWRPdjhuSmpwQ3BfSnplTkhwSW5CZ3DSAXRBVV95cUxQR0ZBQm9PYTBDaExIZjlIRnczNHd2djV6SVBSRzRuaUhZUFBVRWZVbUZ3elVST2d3RjVZazdtdktaNDU0WEFVWE1VcVE3Yk9OQWtCWEZ3d2V1RmkwQllPdnUya05VWHJ5Q3VGUVZ6RkVSTHBzbg?oc=5"
    },
    {
        "id": 12,
        "category": "local",
        "title": "부산시교육청, 방과후학교 동서 격차 해소 나선다",
        "date": "2026.02.13",
        "oneLine": "부산시교육청, 방과후학교 동서 격차 해소 나선다",
        "content": "부산시교육청, 방과후학교 동서 격차 해소 나선다  아시아경제",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTE42YVIxLXp6MXRmdFRleHJUeHcxMEs3U2NkMnFtY2dRZHBTVlVWSUJneWFHekdnQWFiRXlPemRsT0YwLTJXSWFXZmVMTmx3eU9MSnJJNnZrSGdIZEV3aUZTMmpJLTl5emlr?oc=5"
    },
    {
        "id": 13,
        "category": "local",
        "title": "동부교육청, 공무원 성장나무 확대 운영",
        "date": "2026.02.13",
        "oneLine": "동부교육청, 공무원 성장나무 확대 운영",
        "content": "동부교육청, 공무원 성장나무 확대 운영  충청타임즈",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTE1PS1pDR2d1WEVmZktOSDZOeUVpQ1poNURITDJEVkZRRF9uNWREeHBVa0JIU3RTdUpGb1RUZm16am1hMDRCOGZrYS1LT3dIUTB6d3BCc3g4d21OWm9PZ3dKdkR3UjZtRTFY?oc=5"
    },
    {
        "id": 14,
        "category": "local",
        "title": "대구교육청 '과학교육 운영 계획 추진'…기초강화",
        "date": "2026.02.13",
        "oneLine": "대구교육청 '과학교육 운영 계획 추진'…기초강화",
        "content": "대구교육청 '과학교육 운영 계획 추진'…기초강화  뉴시스",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTE1COENVdE5KMWNxbHFBLVJnLUJ1eDZkVkl3WElnbkJMeFJyM2xVNTdIRUtMV09MUTU1Wi1YekZrTmJzeDZObkVlY3ZWNnpadVd0dzAtWHo4Y2daeTRiMHphU3JoVi00ZXE4ckdmNmJKM3NpTVNOaHZfWtIBeEFVX3lxTE1COENVdE5KMWNxbHFBLVJnLUJ1eDZkVkl3WElnbkJMeFJyM2xVNTdIRUtMV09MUTU1Wi1YekZrTmJzeDZObkVlY3ZWNnpadVd0dzAtWHo4Y2daeTRiMHphU3JoVi00ZXE4ckdmNmJKM3NpTVNOaHZfWg?oc=5"
    },
    {
        "id": 15,
        "category": "trend",
        "title": "＂AI 모델 내부 구조 뜯어보자＂…AI 추출·증류 공격 증가",
        "date": "2026.02.13",
        "oneLine": "＂AI 모델 내부 구조 뜯어보자＂…AI 추출·증류 공격 증가",
        "content": "＂AI 모델 내부 구조 뜯어보자＂…AI 추출·증류 공격 증가  한국경제TV 홈페이지",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMifEFVX3lxTFBXSXl1eGRrbThfMVpEcnZNU1RPemRlb19WN1NSWFlJLTA4c19IRmpTdU1ZazJsS2lacFRoSVh5dVNlOWM3Y2JZcldnaFFVU0puYXd5UTU3MnVRX2J4YkpEUGxJVUxvTWVKcjZkVTYwU0JmUWd2V0VMUzBqVl8?oc=5"
    },
    {
        "id": 16,
        "category": "local",
        "title": "부산교육청, 방과후 격차 대책 마련…소규모 학교 지원 확대",
        "date": "2026.02.13",
        "oneLine": "부산교육청, 방과후 격차 대책 마련…소규모 학교 지원 확대",
        "content": "부산교육청, 방과후 격차 대책 마련…소규모 학교 지원 확대  연합뉴스",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE5JZ3p3aFZPSndxNWtneGxxMUFYV3JOazF1ams4VXdHejFXOXVrZmFkZThKWXp4b2RhZFJLWTY0TFlvZzdENEhtRndXMlRXdnZ6WkMwei1xNzlVT0ZfWGY1YdIBYEFVX3lxTE5JZ3p3aFZPSndxNWtneGxxMUFYV3JOazF1ams4VXdHejFXOXVrZmFkZThKWXp4b2RhZFJLWTY0TFlvZzdENEhtRndXMlRXdnZ6WkMwei1xNzlVT0ZfWGY1YQ?oc=5"
    },
    {
        "id": 17,
        "category": "local",
        "title": "부산교육청, '학부모 온라인 아카데미' 운영",
        "date": "2026.02.13",
        "oneLine": "부산교육청, '학부모 온라인 아카데미' 운영",
        "content": "부산교육청, '학부모 온라인 아카데미' 운영  뉴스1",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiX0FVX3lxTE5FOW5KT2MtYTZBLUg0VFdmS0xtWHVxX2tHQ19EYVJRNXJsWGRzX3pBMVVVdHpwNzNoUG4yTE9Ga3NMLVJjcFVYc3dfTUZINklCc2VHR2FzQ25OUW9KQ0h3?oc=5"
    },
    {
        "id": 18,
        "category": "local",
        "title": "대전동부교육청, 지방공무원 성장나무 확대 운영",
        "date": "2026.02.13",
        "oneLine": "대전동부교육청, 지방공무원 성장나무 확대 운영",
        "content": "대전동부교육청, 지방공무원 성장나무 확대 운영  v.daum.net",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiT0FVX3lxTE14Ulhha0lfNGptcEpmNi1ibWdtZDJMWG9aVEpaRElsTTRDcEl5ZDNoUTRYMXhEZ2EzVTJQYV9jOEt4eVVZX2VCN2poaXM3djA?oc=5"
    },
    {
        "id": 19,
        "category": "edutech",
        "title": "웅진씽크빅, AI 학습 플랫폼 '웅진스마트올' 신규 광고 영상 공개",
        "date": "2026.02.13",
        "oneLine": "웅진씽크빅, AI 학습 플랫폼 '웅진스마트올' 신규 광고 영상 공개",
        "content": "웅진씽크빅, AI 학습 플랫폼 '웅진스마트올' 신규 광고 영상 공개  뉴스1",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE5rUmhFMFZQWkpYYWttQjhyNEVHaXk4eEp5aFVabklFTWRleDFuaW1NWDFXY3MxSjJ1OFJYbTF1a1RsX3lmT0tEeFdFM0ZTcWczSnBjOGFydHctdw?oc=5"
    },
    {
        "id": 20,
        "category": "local",
        "title": "경북교육청, ‘디지털 기반 시범유치원’ 공모 추진",
        "date": "2026.02.13",
        "oneLine": "경북교육청, ‘디지털 기반 시범유치원’ 공모 추진",
        "content": "경북교육청, ‘디지털 기반 시범유치원’ 공모 추진  데일리대구경북뉴스",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE4xcFlGblNwdENJSlh3TmdRSkZZM0t0Zmx1M216QjgxSWp3dmRuTE10N2tKazBYMWR6MmdSN2pTYkM4RnVTWG9pNXh0cENDZGEzcUdtMWZqdXM4bzVnT19zVXc0elYtUQ?oc=5"
    },
    {
        "id": 21,
        "category": "trend",
        "title": "AI 파고에 갈린 빅테크…MS \"화이트칼라 1년내 자동화\" vs AWS \"SaaS 위기 과장\"",
        "date": "2026.02.13",
        "oneLine": "AI 파고에 갈린 빅테크…MS \"화이트칼라 1년내 자동화\" vs AWS \"SaaS 위기 과장\"",
        "content": "AI 파고에 갈린 빅테크…MS \"화이트칼라 1년내 자동화\" vs AWS \"SaaS 위기 과장\"  청년일보",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiZ0FVX3lxTE5xczV4bU9LMXM2bDJyU1lXRTRpdHBiXzlqVkM1a3ZoODE2NUI3NnBISzNyTXd5Q0dMY0NxUzlmYkZjbEEwdUhqR3VDUmI2M2xIa1hobmVhZXlkRWZOVE1yQkItZlhiMnM?oc=5"
    },
    {
        "id": 22,
        "category": "trend",
        "title": "AI, 대학 교육인프라로 확산… 캠퍼스가 주도권 경쟁 무대로",
        "date": "2026.02.13",
        "oneLine": "AI, 대학 교육인프라로 확산… 캠퍼스가 주도권 경쟁 무대로",
        "content": "AI, 대학 교육인프라로 확산… 캠퍼스가 주도권 경쟁 무대로  IT조선",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMidEFVX3lxTE0wMVJHZnU0c3BkdUo0M3NCdU1QSXpzWXA3ZHBENzlieXBLdTNOUUtDRjlseHZ1U18wOG1JUXU0MUJqbTlvZTF6Qmwyb3RBV2FwVHAtWk12aldkTm9IemVtaFBfME03ZzlCVGtOcG9ETHk1a0lf0gF0QVVfeXFMTTAxUkdmdTRzcGR1SjQzc0J1TVBJenNZcDdkcEQ3OWJ5cEt1M05RS0NGOWx4dnVTXzA4bUlRdTQxQmptOW9lMXpCbDJvdEFXYXBUcC1aTXZqV2ROb0h6ZW1oUF8wTTdnOUJUa05wb0RMeTVrSV8?oc=5"
    },
    {
        "id": 23,
        "category": "trend",
        "title": "\"AI가 산업 대체\" vs \"기존산업 성장\"…빅테크CEO '엇갈린 시선'",
        "date": "2026.02.13",
        "oneLine": "\"AI가 산업 대체\" vs \"기존산업 성장\"…빅테크CEO '엇갈린 시선'",
        "content": "\"AI가 산업 대체\" vs \"기존산업 성장\"…빅테크CEO '엇갈린 시선'  연합뉴스",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE1XOC1seHB1cVZHYTc3aDdPMl9DeVVHSUh4bl9La0YtVTZTbTVJc3ZITi1YTHl0T3E3U1kyR3dMcWdSTGJmWUhrWGNheXYyd0sxZ3kxT3cybUFFVmFZWHB5MdIBYEFVX3lxTE1XOC1seHB1cVZHYTc3aDdPMl9DeVVHSUh4bl9La0YtVTZTbTVJc3ZITi1YTHl0T3E3U1kyR3dMcWdSTGJmWUhrWGNheXYyd0sxZ3kxT3cybUFFVmFZWHB5MQ?oc=5"
    },
    {
        "id": 24,
        "category": "trend",
        "title": "[AI 뉴스] 대화는 끝났다, 이제는 문서다”…오픈AI, 딥 리서치 ‘전체 화면 뷰어’ 도입",
        "date": "2026.02.13",
        "oneLine": "[AI 뉴스] 대화는 끝났다, 이제는 문서다”…오픈AI, 딥 리서치 ‘전체 화면 뷰어’ 도입",
        "content": "[AI 뉴스] 대화는 끝났다, 이제는 문서다”…오픈AI, 딥 리서치 ‘전체 화면 뷰어’ 도입  아웃소싱타임스",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMickFVX3lxTE1fcmhzbEc0b2lUYmFPbzZQbVhSdzJQZHlnQnZ6WUdjWkJZS010bWg1N1FSYk9LZ2ZncGw4RnY4aG1mT29feHFGb0hIekt5bEhmdEUxMmI5WFd5Mzd0SGhhZUphTWZKOU0xS0owLUNjc0JXUQ?oc=5"
    },
    {
        "id": 25,
        "category": "policy",
        "title": "19문항 갈아치운 '수능 영어', 우연 아닌 '불수능' 피해는 수험생",
        "date": "2026.02.13",
        "oneLine": "19문항 갈아치운 '수능 영어', 우연 아닌 '불수능' 피해는 수험생",
        "content": "19문항 갈아치운 '수능 영어', 우연 아닌 '불수능' 피해는 수험생  뉴스후플러스",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMibkFVX3lxTE4zbS10bEJsdVRuT3VrUmxYV1Y1R0tYcG9TdlJLY0Q4WXl0bGhqRWNWaTBaWGVUN1NzazZ0NFVmb0lSWF82Sy1rSnA5QjI1Q1Q2UFo4T1Y3aThPOEdOeU03cUx5bHZ5XzB1cHFkQnNR?oc=5"
    },
    {
        "id": 26,
        "category": "policy",
        "title": "수능에도 입성한 AI…내년 모평부터 영어지문 출제 맡긴다",
        "date": "2026.02.13",
        "oneLine": "수능에도 입성한 AI…내년 모평부터 영어지문 출제 맡긴다",
        "content": "수능에도 입성한 AI…내년 모평부터 영어지문 출제 맡긴다  MSN",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiiwRBVV95cUxPcDI3Ti1kVkM1U3VwTDZFTy1WS2FiTTY5VHRrOHFoNGEyZUdST1Q3Zjh3RklKTHhXWWsyTVJ3aENMd1RVV1FhbzlKMDV4UnpUOTAwVXpTQTMtT1pOSEp3eWJYX0dRY294T3BWN1NGZ0R6WkQ5RlRyZVNWTFpvTjZwRnB4bXc1Z2xjeWVvT2NTU2ZKV0tzNC1OSjZJS2lpRkJzMU5wcEhiWE1EMnB5TGNpUTZ3aS00YkRvR3JjT2kyaVJZSVVKWl92UHZkcnNzV1JWbDY0eGQ2dUw3VWtYbGRSMjRWTlZmOExtZUl2NlRMYWRaVEtqTGhQUDQ3OWlFdHhIdnU1ckVXOVlnVGhZWnFJRmpLX01oUV9lczFzemVTR3lSRU13Mm5GeHl1V1drRkFDYm5TMWdpUFdKc0dGbVpISzVyX2s2SEFNdlRKZlJ0OFlraUtidkprM1lWeXAtLTB1WFpreDJoN0N5eE80dUF4b0c1UXQ3M3FUdl9iT0RtUmRwWm5kdm5BcDVwc3BBZWkxanJ2ajlEZ2xKNU1KYWlRdi1WNEtUWGZ1cGpRSVN5UjVaRlpZdm1vNFYyOWtGMFg4dkpoWmg3TjlOR1NnMWVodXpLVDNFTjZQWGxPdFU3VnIwUGRybGI1dXFnemN3ckIwc2lOTGhKZ3NyWldTamZzeTh5NGk5TV9YbFZ3?oc=5"
    },
    {
        "id": 27,
        "category": "policy",
        "title": "AI가 수능 영어 지문 만든다",
        "date": "2026.02.13",
        "oneLine": "AI가 수능 영어 지문 만든다",
        "content": "AI가 수능 영어 지문 만든다 - 교육부, 2028년부터 출제 패러다임 전환 선언  한국공공정책신문",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiQ0FVX3lxTE1USHp3dXlhWklQd1otWTkzSmZfQXEtWEEyOXhzbXVPVVA1YS1WMEpPNC1Ic2RYVHhhV25XT28zWDF4NUk?oc=5"
    },
    {
        "id": 28,
        "category": "policy",
        "title": "'불영어' 방지 대안 낸 교육부 \"AI로 지문 만들고 검토한다\"",
        "date": "2026.02.12",
        "oneLine": "'불영어' 방지 대안 낸 교육부 \"AI로 지문 만들고 검토한다\"",
        "content": "'불영어' 방지 대안 낸 교육부 \"AI로 지문 만들고 검토한다\"  MSN",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiggRBVV95cUxNOVowU2hIOU9KVFFqMmUxMm5RZDBYNlFQRDQ5Z3VzeF8wb0IwZVBNeGtVclJURExiYUZvUnpac21SNHJvOGZYVEhsVGFaS0NBOU9MR2F1STQ5b3Zqc2Uxb3ZXZVM4Yk1UR0tFZzRVekRrUURfZ1dfbjAwbGlkZTN5TU1xR2stcjZmdHhUeHZWRXE4TG5HalZHbEVLLWxtVUV4NzdTZkxqMndXallWWnJzaVJuRy0yUTNPeFZoWkFWSEZVUTBIbFVHdk9jV0ZtTlBDVll2TUp4ZGtRb1Jta1dMbEdnWFlOZDJxajQ5czZDbzFBNkhSRWNGRHkyckVycEpWaW1uc251WTBKOVc0cDhTbjhqOWNCNGNqWE5mcHNsemhuekZmbDFzNjYydGFrc0JCZkZYUWk0QXVLTko5dm96VW16TzhsV3FPZzMzMjlIUlQtMHBSdU9mOVpJOURMc1VkWHBNTnhMamVnckdRMmR3M01jZzU3WWIxeW5NZmM0aHRSU1ZNb25JSHlZeVVMel9tVE1yNXRfWFVfcWlTdTd1aHp6N0pVNTdBWFU3dXNsdUE0cnI5c0sxeDdnd2NPMGUzSDNxc0pxTGtWWktqbGJMR2FlQVBudXctOEV0eG1fY01ZeVhudWZhSWRlQWNDWHBhaUR0WnBwbEM4STg2Y1lVV0tR?oc=5"
    },
    {
        "id": 29,
        "category": "policy",
        "title": "교육부, 수능 영어 ‘역대 최저 1등급’ 사태 후 출제 시스템 전면 개편",
        "date": "2026.02.12",
        "oneLine": "교육부, 수능 영어 ‘역대 최저 1등급’ 사태 후 출제 시스템 전면 개편",
        "content": "교육부, 수능 영어 ‘역대 최저 1등급’ 사태 후 출제 시스템 전면 개편  파이낸셜투데이",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMibkFVX3lxTFA2YlpzTFQyVVJwejVDZG5LVkQxTkJtdnBIOUhjM2poUl9VakJaSmR1dmItdldvbDNueDh5QzVkNWVkMU9WNGU3M1FGSjlFWnlsQWhPemVyakp4STlqLURmbHBtam91dm9TTFdSM2R30gFuQVVfeXFMUDZiWnNMVDJVUnB6NUNkbktWRDFOQm12cEg5SGMzamhSX1VqQlpKZHV2Yi12V29sM254OHlDNWQ1ZWQxT1Y0ZTczUUZKOUVaeWxBaE96ZXJqSnhJOWotRGZscG1qb3V2b1NMV1IzZHc?oc=5"
    },
    {
        "id": 30,
        "category": "edutech",
        "title": "경기지역 퇴직 교원들, ‘경기교육의 본질 회복’ 모색",
        "date": "2026.02.12",
        "oneLine": "경기지역 퇴직 교원들, ‘경기교육의 본질 회복’ 모색",
        "content": "경기지역 퇴직 교원들, ‘경기교육의 본질 회복’ 모색  프레시안",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE1Ec1l2dmFHeUhSSDJjaEp4dktsdlluTGtrVm52dDVrZUpldVN3T2JSLWRid2l2Zi1hRkNQblVFaS1YUldGNUlobW1ZNHAteXpTbXFjblZmR2VESzZLZVRQUEpjNC1EdE1WYm1v?oc=5"
    },
    {
        "id": 31,
        "category": "policy",
        "title": "교육부, AI로 수능 출제 부담↓…보안 우려엔 “별도 서버 구축해 운영”",
        "date": "2026.02.12",
        "oneLine": "교육부, AI로 수능 출제 부담↓…보안 우려엔 “별도 서버 구축해 운영”",
        "content": "교육부, AI로 수능 출제 부담↓…보안 우려엔 “별도 서버 구축해 운영”  투데이신문",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMib0FVX3lxTE1HNU8wS2FJSnRaUVZoWkpFYTFpS3M2N3l3NkRxNW5Bcm1BY2VTY2F0eE9TLURMbHVUYnV4SlJsZ1V3YjRQaGtCWTJmU183aTRfemp1VHY5bWlBa053eWFyNW1zT281blkwRFVJdk5wQdIBb0FVX3lxTE1HNU8wS2FJSnRaUVZoWkpFYTFpS3M2N3l3NkRxNW5Bcm1BY2VTY2F0eE9TLURMbHVUYnV4SlJsZ1V3YjRQaGtCWTJmU183aTRfemp1VHY5bWlBa053eWFyNW1zT281blkwRFVJdk5wQQ?oc=5"
    },
    {
        "id": 32,
        "category": "trend",
        "title": "'수익화'에 올인한 오픈AI…해고·퇴사·감시 등 내부 진통 잇달아",
        "date": "2026.02.12",
        "oneLine": "'수익화'에 올인한 오픈AI…해고·퇴사·감시 등 내부 진통 잇달아",
        "content": "'수익화'에 올인한 오픈AI…해고·퇴사·감시 등 내부 진통 잇달아  AI타임스",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiakFVX3lxTFBZNDdZRG5DM2Q5eU94ZERZYldpdUFKbFQ1Y21FNFBSRmtod3FNYVpiV1REWFJBckIydVN6Sl9iM0pRWDdJWTZlb0xSMVVxaldmNnZZQU5zd3NsWmxfSEpZZzNmdXZfZncxakE?oc=5"
    },
    {
        "id": 33,
        "category": "policy",
        "title": "AI가 만드는 수능 영어 지문... 불수능 논란 잠재울까? [영상]",
        "date": "2026.02.12",
        "oneLine": "AI가 만드는 수능 영어 지문... 불수능 논란 잠재울까? [영상]",
        "content": "AI가 만드는 수능 영어 지문... 불수능 논란 잠재울까? [영상]  한국일보",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMic0FVX3lxTE1LWkFfS19wVHVCUTk2Y1BiZzJxLVVNQ2hxX29mX2w0amFkYlRtcXhlcUJQTWdJOVBvcWs5UFpYUE11SzJBdnJ2NXJFX0NqQVlmWkF5THktQ3BOYmw5bjdDaVN4dUZTTGtyVjhrSC1oaXc2M3M?oc=5"
    },
    {
        "id": 34,
        "category": "trend",
        "title": "\"제미나이 통한 해킹 늘어\"…구글 보안 그룹의 경고",
        "date": "2026.02.12",
        "oneLine": "\"제미나이 통한 해킹 늘어\"…구글 보안 그룹의 경고",
        "content": "\"제미나이 통한 해킹 늘어\"…구글 보안 그룹의 경고  한국경제",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiVEFVX3lxTFBfdTIzNGgwS1NlcEZITkFUYXFNWmFEMDlyRVBSc0duU0kwbG9ySDgwd2g3SDBzdDhsOFZXX3BQQW5hUVRFa1NhcklSN2tlQmZDSU9qNNIBVEFVX3lxTFBfdTIzNGgwS1NlcEZITkFUYXFNWmFEMDlyRVBSc0duU0kwbG9ySDgwd2g3SDBzdDhsOFZXX3BQQW5hUVRFa1NhcklSN2tlQmZDSU9qNA?oc=5"
    },
    {
        "id": 35,
        "category": "iscream",
        "title": "[KFE 유통로그]교원 플래너스어학원·아이스크림미디어 하이클래스, 신학기 수요 겨냥",
        "date": "2026.02.12",
        "oneLine": "[KFE 유통로그]교원 플래너스어학원·아이스크림미디어 하이클래스, 신학기 수요 겨냥",
        "content": "[KFE 유통로그]교원 플래너스어학원·아이스크림미디어 하이클래스, 신학기 수요 겨냥  한국금융경제신문",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFBDa2UxQnNoVnkyR3pLNGlyaGlLcUFNdnhmNjJCZmZpelRMQ2Y4VmtTQk5wRFV2bGtuQ2dxbFlEZjNpMjAwbV9QLVBrUGEwNERnXzlEWlFRRHVQV0VWZ1dZeVpyR2V2Y1VyVHc0TUotTjLSAXBBVV95cUxQQ2tlMUJzaFZ5Mkd6SzRpcmhpS3FBTXZ4ZjYyQmZmaXpUTENmOFZrU0JOcERVdmxrbkNncWxZRGYzaTIwMG1fUC1Qa1BhMDREZ185RFpRUUR1UFdFVmdXWXlackdldmNVclR3NE1KLU4y?oc=5"
    },
    {
        "id": 36,
        "category": "edutech",
        "title": "[에듀플러스]비상교육, 대한민국 교육박람회 'AI 디지털 교육자료' 수업 공모전 대상 교사 웨비나 개최",
        "date": "2026.02.12",
        "oneLine": "[에듀플러스]비상교육, 대한민국 교육박람회 'AI 디지털 교육자료' 수업 공모전 대상 교사 웨비나 개최",
        "content": "[에듀플러스]비상교육, 대한민국 교육박람회 'AI 디지털 교육자료' 수업 공모전 대상 교사 웨비나 개최  전자신문",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTFB2VUg3OURvc2ViZVU1S2J3Y0Q4ekhDZlpEOGpnV09EZ3QtaS1QckRkNlRJTGJXUDBjeFRuVnQtdXNUY0ZoVVduV0c5SHY5QQ?oc=5"
    },
    {
        "id": 37,
        "category": "edutech",
        "title": "비상교육, 신학기 대비 'AI 디지털 교육자료 준비법' 웨비나 개최",
        "date": "2026.02.12",
        "oneLine": "비상교육, 신학기 대비 'AI 디지털 교육자료 준비법' 웨비나 개최",
        "content": "비상교육, 신학기 대비 'AI 디지털 교육자료 준비법' 웨비나 개최  하이테크정보",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTE5EVmZ4cjFOTHFKakpYVklEUkQ5SFlDcjMtcUFkQW9lVzVBVUR1LTYyREprbWxKRFlSb291YWdKRTl2ZndNeV9sYjZFX3pDb3A5b3pjZjNzaXRWREtYdFhtN3Rzd2xXQndC0gFsQVVfeXFMTzcwS1RGWWJmLTJHSy0zYXMzeXZ6SHpjT25sTkpBNHh3UXFuUjdPdWtuTUF1bVMxNXpNRlJ0SHJhaHUwUFlFc0wzQ1dWZXhfUllRTVE0R1g2SjVITkxSM0ZoZ0ZTZG4tS082amNI?oc=5"
    },
    {
        "id": 38,
        "category": "edutech",
        "title": "AI로 여는 개인맞춤 교육…15조원 새 시장이 열린다",
        "date": "2026.02.12",
        "oneLine": "AI로 여는 개인맞춤 교육…15조원 새 시장이 열린다",
        "content": "AI로 여는 개인맞춤 교육…15조원 새 시장이 열린다  한국경제",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE54UW0ybV9pY3ZiUlBteFFZX1A1SzFCTS1BRDRYczhHZ1ItU3VMSGNsQTlSQXRUSXd1Qk5kZ3FXQzV5VER0djdLNFlmaFRXOHFQdjJ5X9IBVEFVX3lxTE54UW0ybV9pY3ZiUlBteFFZX1A1SzFCTS1BRDRYczhHZ1ItU3VMSGNsQTlSQXRUSXd1Qk5kZ3FXQzV5VER0djdLNFlmaFRXOHFQdjJ5Xw?oc=5"
    },
    {
        "id": 39,
        "category": "policy",
        "title": "고교학점제에 AI 수능까지…09년생 수험생 · 학부모 “또 바뀌나” 한숨",
        "date": "2026.02.12",
        "oneLine": "고교학점제에 AI 수능까지…09년생 수험생 · 학부모 “또 바뀌나” 한숨",
        "content": "고교학점제에 AI 수능까지…09년생 수험생 · 학부모 “또 바뀌나” 한숨  르데스크",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiVkFVX3lxTE9CSl9EWHVCZF9BSm9iSDA4NmVpdm9RMlN5TlJMNnJ6TzNhMWg5MjRoQ08tT1hCSnIybng0QWJHaVpweTRTandMa3ZLa0trUm9na0hEWG1R?oc=5"
    },
    {
        "id": 40,
        "category": "policy",
        "title": "국·수·탐 오를 때 영어만 후진…N수생 25% 등급 하락",
        "date": "2026.02.12",
        "oneLine": "국·수·탐 오를 때 영어만 후진…N수생 25% 등급 하락",
        "content": "국·수·탐 오를 때 영어만 후진…N수생 25% 등급 하락  금강일보",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTE9LN1paZFRLS3FYem9aMzF0RHhVQ0V0VUNVM3FJdEx3UXZGZzJPTEVieUQ1bkJCSXFzc0ZtcW8wMXV6SVNKZmpLUTFTUUFsd0pHc3l4WHc5UG9taFpuS0dBczhnUzBJeGg1?oc=5"
    },
    {
        "id": 41,
        "category": "edutech",
        "title": "AI-DLC 기반 웅진씽크빅 북큐레이터 AI 에이전트 구축",
        "date": "2026.02.12",
        "oneLine": "AI-DLC 기반 웅진씽크빅 북큐레이터 AI 에이전트 구축",
        "content": "AI-DLC 기반 웅진씽크빅 북큐레이터 AI 에이전트 구축  Amazon Web Services (AWS)",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMif0FVX3lxTE9rSkV4WDFOendOYjBHVEg2S01CRFYxLXZMVldwd0E4QVlPa1NpaVVzekttYUhacjdaUmMtWENGTlJTYVg1ZHRRWDIwNGtKNGFpbEhscXBBTDlzbUlpc1NtWGZqSFh3NHVLZ1M2b2puU3NlSl90WHJBSHVsQ0VuZG8?oc=5"
    }
];