const newsData = [
    {
        "id": 1,
        "category": "edutech",
        "title": "대교, TWS 협업 '써밋 스타런' 선봬",
        "date": "2026.02.13",
        "oneLine": "대교, TWS 협업 '써밋 스타런' 선봬",
        "content": "대교, TWS 협업 '써밋 스타런' 선봬  신아일보",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMib0FVX3lxTFBrMGt5LVBiaG5waWdpN3M5Mk1YS1VIZHpKZnJ0VmQ1OWRlamZLbkZjTlk5bW1VVjh6SU5RVTE0UEtOQ2YxQ29MSkFIRkVCMFRPZFpYcjAzV2RfR1gtTjVVQldkRjJHOU1vYVNZMXlBdw?oc=5"
    },
    {
        "id": 2,
        "category": "trend",
        "title": "이원택 의원, 생성형AI 지원·창업 투자 확대... “청년 기회 늘린다”",
        "date": "2026.02.13",
        "oneLine": "이원택 의원, 생성형AI 지원·창업 투자 확대... “청년 기회 늘린다”",
        "content": "이원택 의원, 생성형AI 지원·창업 투자 확대... “청년 기회 늘린다”  이로운넷",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE12OVFOTHVFSzN5VDJTSzVkZmp6LUhHSm5VOUdxdGRMa3V2YTFoYUppdVdVUUVCTXVONlJyNF9PWko0dERuU1pMNFVIaDdKaFYwZWlFc1NkbEltMWlhUndtbnl1Mllhdw?oc=5"
    },
    {
        "id": 3,
        "category": "edutech",
        "title": "성신여대 사범대학 및 교육대학원, 6주기 교원양성기관 역량진단 A등급 획득",
        "date": "2026.02.13",
        "oneLine": "성신여대 사범대학 및 교육대학원, 6주기 교원양성기관 역량진단 A등급 획득",
        "content": "성신여대 사범대학 및 교육대학원, 6주기 교원양성기관 역량진단 A등급 획득  베리타스알파",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTFBWcDJpbFVoS2hxZjhJeGYtREtRTnl2ZU5Ka0Jld3NxT3pUNzVwUHVTOGlFRWtmUGhQU0kxcTM2d3ozUGFlVE9RQmJLdWlwdnVwU2VrMWRJaE8tWWFoX3I4ay1OTFJyeXU1VlUw?oc=5"
    },
    {
        "id": 4,
        "category": "trend",
        "title": "오픈AI “中 딥시크, 美 AI가 만든 결과물 무단으로 빼가”",
        "date": "2026.02.13",
        "oneLine": "오픈AI “中 딥시크, 美 AI가 만든 결과물 무단으로 빼가”",
        "content": "오픈AI “中 딥시크, 美 AI가 만든 결과물 무단으로 빼가”  동아일보",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMib0FVX3lxTFAwbXFBS2FHWW9SRjNuV0swUDF1aFMtbV9MeHVRTzhaVGwydXNCRlloWmw4N2oxUG9MR0xiMHUxdDBwZDJIN05sS0pWUHNGTVFIUG1fMGhpVUxnbHYxdWxKMmxpeGdmQ1Fjekp5aHRCMNIBZkFVX3lxTE9fRVp5T0RfUUJpWXAxQ1doN3R2N0plNlBZcnluWmc0R0tpek5JVFpNbWtnR0RISzB0YzZ1T1BEZklxblZEMC1sS0FNMHBoLUE1aFhmaW5DNDJXcU1yMGNUcC1fX3hYZw?oc=5"
    },
    {
        "id": 5,
        "category": "edutech",
        "title": "일산대교 등 경기 민자도로 3곳 설연휴 무료통행…4일간 무료",
        "date": "2026.02.13",
        "oneLine": "일산대교 등 경기 민자도로 3곳 설연휴 무료통행…4일간 무료",
        "content": "일산대교 등 경기 민자도로 3곳 설연휴 무료통행…4일간 무료  중앙일보",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiVkFVX3lxTE1MbjlCNVQwN3ZmMk4ydWt2TFdNT2RIUmZrOTBFSDFWeE92dDR2aXAydWtsWC1lYmtTM1RSRkhyZFBkNDd6NG9MT21NQ3lZSnNaUk1yMjBR?oc=5"
    },
    {
        "id": 6,
        "category": "local",
        "title": "이서영 경기도의원, “16년 방치된 삼평동 옛 이황초 부지, 550억 규모 ‘교육복합문화센터’로 화려한 부활”",
        "date": "2026.02.13",
        "oneLine": "이서영 경기도의원, “16년 방치된 삼평동 옛 이황초 부지, 550억 규모 ‘교육복합문화센터’로 화려한 부활”",
        "content": "이서영 경기도의원, “16년 방치된 삼평동 옛 이황초 부지, 550억 규모 ‘교육복합문화센터’로 화려한 부활”  화성저널",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiZEFVX3lxTE5fZVFkNThkNjB5TTJpaHlOeWF2TGhLMkZ2a0I1ZmpjV29fc2RWNTNRYXM0NE5VQVQzS0NySTFnaG40em5lb2J3MWxMMmtvdzNxbHBLa0hMenViUzBPR1RhRU1rN3I?oc=5"
    },
    {
        "id": 7,
        "category": "edutech",
        "title": "도교육청, ‘AI+X’ 융합 교육 가속화…직업계고 교원 200명 실무 연수",
        "date": "2026.02.13",
        "oneLine": "도교육청, ‘AI+X’ 융합 교육 가속화…직업계고 교원 200명 실무 연수",
        "content": "도교육청, ‘AI+X’ 융합 교육 가속화…직업계고 교원 200명 실무 연수  화성신문",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiQkFVX3lxTFBwY2syVUV2RlE5RVE4WE0xZHNMWjB5VWJuODBDSmZ3WVQ5WHAzX09pVzdwVkpsbFV2LUIxNjJZcFNIZw?oc=5"
    },
    {
        "id": 8,
        "category": "trend",
        "title": "\"30만원짜리가 2만9000원\"…깜짝 할인에 '카톡' 들썩였다",
        "date": "2026.02.13",
        "oneLine": "\"30만원짜리가 2만9000원\"…깜짝 할인에 '카톡' 들썩였다",
        "content": "\"30만원짜리가 2만9000원\"…깜짝 할인에 '카톡' 들썩였다  한국경제",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE1GSmVNSDhQSmFsT015OURaMERPa3BPV2ZiSXpLRVM0WVRtWk9TNk9Da2pIX2pFV3NfSHluU3duSnd1cHkwWlpicG9FeG5ubWtPTExrdTFvbFFrQdIBVEFVX3lxTE5FMVhJakpVSnkxSzVjVEJSaU1tZUN3clBsaUhKc2tqSlpWMjRsRzdKZWpUdThlSlFBcUFxS2ZIVlV1MXVWSFBiSHVCT0Y3MjVGenlnZg?oc=5"
    },
    {
        "id": 9,
        "category": "local",
        "title": "촘촘한 주말 유아 돌봄…보호자 양육 부담 덜어준다",
        "date": "2026.02.13",
        "oneLine": "촘촘한 주말 유아 돌봄…보호자 양육 부담 덜어준다",
        "content": "촘촘한 주말 유아 돌봄…보호자 양육 부담 덜어준다  뉴스N제주",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTFAwRkhITUdmekMyRWxaNzQ3R0lnTV81Zm4xLThzMkFvMDBMaDVqVTVxcDN2V1FubFFnZS1BNWJsam5EQUVZcVVqQ2dJbTZrSFo4dzA5WnItWUhVZTAzR1NCamFWUmdVWGZ1UjZz?oc=5"
    },
    {
        "id": 10,
        "category": "trend",
        "title": "[붓다, AI 윤리에 답하다] ④ AI는 인간 노동의 종말을 가져 올 것인가",
        "date": "2026.02.13",
        "oneLine": "[붓다, AI 윤리에 답하다] ④ AI는 인간 노동의 종말을 가져 올 것인가",
        "content": "[붓다, AI 윤리에 답하다] ④ AI는 인간 노동의 종말을 가져 올 것인가  현대불교",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMib0FVX3lxTFBvQUhrdTAxdlRTU3ZBUmx5aVZ2RUZ6U3RXcUtWWUxrNnI2VDJNT3FDUk1Gc2taT0F0WE15eVZpRFp6UFlSZnZsUC1kV3g5T0txZEJPRmZWalhabG9UM29jaXdYLXRPWDBnTk9QY3JObw?oc=5"
    },
    {
        "id": 11,
        "category": "policy",
        "title": "중앙선거관리위원회, 중앙당 소재지 등 허위 신고한 중앙당 대표자 고발",
        "date": "2026.02.13",
        "oneLine": "중앙선거관리위원회, 중앙당 소재지 등 허위 신고한 중앙당 대표자 고발",
        "content": "중앙선거관리위원회, 중앙당 소재지 등 허위 신고한 중앙당 대표자 고발  프레스뉴스",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMic0FVX3lxTE9zOUp2MVZDQVZURzhuaC0wNE9qaHlHVjNDY2Vxb1NoSlRxbDFoUkhJUjVIOEl4X3ktdXVtT0swRWJfYWxrUU9BQi1MR3RPNUgwTGN3cEdHSTFKMXJ1bEg2UUpnaThJb1hiaUh2V2tmN3hxU3c?oc=5"
    },
    {
        "id": 12,
        "category": "trend",
        "title": "\"12시간 업무 20분이면 끝\"…LG CNS·오픈AI가 제시하는 기업AX",
        "date": "2026.02.13",
        "oneLine": "\"12시간 업무 20분이면 끝\"…LG CNS·오픈AI가 제시하는 기업AX",
        "content": "\"12시간 업무 20분이면 끝\"…LG CNS·오픈AI가 제시하는 기업AX  지디넷코리아",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiVkFVX3lxTFBnWmNtMExETGVGR2xHWmlaSzNJbi0xZ05zMWJ4WU9ybFBTR1R5ODVmWVpkY1NaT0ViMWZHZWVkbEotT0RhR3kyZ2xZZlFkTXpjejdaazF3?oc=5"
    },
    {
        "id": 13,
        "category": "edutech",
        "title": "대교, TWS와 함께하는 공부 응원 프로젝트 ‘대교 써밋 스타런’ 론칭",
        "date": "2026.02.13",
        "oneLine": "대교, TWS와 함께하는 공부 응원 프로젝트 ‘대교 써밋 스타런’ 론칭",
        "content": "대교, TWS와 함께하는 공부 응원 프로젝트 ‘대교 써밋 스타런’ 론칭  매일일보",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiZEFVX3lxTE9zZTJOanBFcENxeTV1amNmM19ZbkNDTXFlWEo5OUxFdG5VenBIc3NacS1fLWZEcURxbWJsdTR3S1ozTWdaR1gxUWt1eTVSVEJVVkhZOG1Wa1BPQVRhQ05vOTZsX3I?oc=5"
    },
    {
        "id": 14,
        "category": "trend",
        "title": "오픈AI, '세레브라스 칩 구동' 첫 AI모델 공개…엔비디아 경쟁사",
        "date": "2026.02.13",
        "oneLine": "오픈AI, '세레브라스 칩 구동' 첫 AI모델 공개…엔비디아 경쟁사",
        "content": "오픈AI, '세레브라스 칩 구동' 첫 AI모델 공개…엔비디아 경쟁사  연합뉴스",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE1VVnpsM2J4d3ZtZm8wZms1MlhDR0NEV191a21Ta0lNM01PWU81Qi1oaGVmWU1kM3JiWlBjNGdPWldBTzBhTXY1OGhmNkFjWTFkR3R6Q0NxZ2o0bjZuV2NocNIBYEFVX3lxTE1VVnpsM2J4d3ZtZm8wZms1MlhDR0NEV191a21Ta0lNM01PWU81Qi1oaGVmWU1kM3JiWlBjNGdPWldBTzBhTXY1OGhmNkFjWTFkR3R6Q0NxZ2o0bjZuV2NocA?oc=5"
    },
    {
        "id": 15,
        "category": "iscream",
        "title": "웅진씽크빅, -0.59% VI 발동",
        "date": "2026.02.13",
        "oneLine": "웅진씽크빅, -0.59% VI 발동",
        "content": "웅진씽크빅, -0.59% VI 발동 - 조선비즈  Chosunbiz",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxNVF9uS1VHaHRuR0YyR1dGb2FHVWlxVmk5NG1ySGE3VXprcFB1VjV3Rk9QX3hvNzJTbDUyeGJ2WmNDVW41UG1LSlc3NXA4d2drODVNUFZJTTlvX3NrNTdxaTE5S3JCbTVscXZMb2ljSTh4b092YVN0N2ZXZ0VXVTlZd3o4VXB1TnVfYlFKbWhEd2k4M25uUzlz0gGXAUFVX3lxTE1UX25LVUdodG5HRjJHV0ZvYUdVaXFWaTk0bXJIYTdVemtwUHVWNXdGT1BfeG83MlNsNTJ4YnZaY0NVbjVQbUtKVzc1cDh3Z2s4NU1QVklNOW9fc2s1N3FpMTlLckJtNWxxdkxvaWNJOHhvT3ZhU3Q3ZldnRVdVOVl3ejhVcHVOdV9iUUptaER3aTgzbm5TOXM?oc=5"
    },
    {
        "id": 16,
        "category": "iscream",
        "title": "\"다시 독서 권하는 시대\"…AI 대세 속, 아이들 책 읽히기 나서는 교육업계",
        "date": "2026.02.13",
        "oneLine": "\"다시 독서 권하는 시대\"…AI 대세 속, 아이들 책 읽히기 나서는 교육업계",
        "content": "\"다시 독서 권하는 시대\"…AI 대세 속, 아이들 책 읽히기 나서는 교육업계  네이트",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE9yZjN2cW5WeldxcE1Pd2VGSktDanhaR2V4SEpCTGVzOFJPaEx6LW1DSF9JNmlXWTUwYlZnNXlFcHNwNDVnYVdWTl85NWJob096ZXlv?oc=5"
    },
    {
        "id": 17,
        "category": "edutech",
        "title": "메가스터디학원, 2027학년도 N수 정규반 개강",
        "date": "2026.02.13",
        "oneLine": "메가스터디학원, 2027학년도 N수 정규반 개강",
        "content": "메가스터디학원, 2027학년도 N수 정규반 개강  v.daum.net",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiVEFVX3lxTFBzX24xQjhNeWxVbDY4Ujg4QjRBa0dfaW5YenpHR1o0cktDXzJQbUpSRnFuVXFvN3ZXT2JpdEkxaFd0RGx5Z3RlMm9RXzNYTTVqT2gyaw?oc=5"
    },
    {
        "id": 18,
        "category": "edutech",
        "title": "웅진씽크빅, AI 학습 플랫폼 '웅진스마트올' 신규 광고 영상 공개",
        "date": "2026.02.13",
        "oneLine": "웅진씽크빅, AI 학습 플랫폼 '웅진스마트올' 신규 광고 영상 공개",
        "content": "웅진씽크빅, AI 학습 플랫폼 '웅진스마트올' 신규 광고 영상 공개  뉴스1",
        "importance": "이 이슈는 아이스크림미디어의 기존 에듀테크 사업 모델에 직접적인 영향을 줄 수 있는 중요한 변화입니다. 특히 공교육 디지털 전환 정책과 맞물려 시장의 판도가 바뀔 가능성이 높으므로, 경쟁사의 대응 현황을 면밀히 모니터링하고 자사의 차별화된 기술력(AI 튜터 등)을 부각할 수 있는 방안을 모색해야 합니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE5rUmhFMFZQWkpYYWttQjhyNEVHaXk4eEp5aFVabklFTWRleDFuaW1NWDFXY3MxSjJ1OFJYbTF1a1RsX3lmT0tEeFdFM0ZTcWczSnBjOGFydHctdw?oc=5"
    },
    {
        "id": 19,
        "category": "trend",
        "title": "“AI가 엑셀 잡아먹어”… 위기의 MS",
        "date": "2026.02.13",
        "oneLine": "“AI가 엑셀 잡아먹어”… 위기의 MS",
        "content": "“AI가 엑셀 잡아먹어”… 위기의 MS  조선일보",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMigwFBVV95cUxPb2dYR3ZqZl9BZl96N3dPcmFrRWgwcjBXejNCX19UR3lhbnA1UDQtbUlHSmhBSjJWVmZ3VVBwUUxTWVVoZmQ0akwwOGxoTUp2c2h4UGNOS09xZzRHaHN6N3d0Y3VjR0tEdVRzbDdVM0FPejAxR1FmVXFpV3VYQVc3TTZyd9IBlwFBVV95cUxQaC05U0NGYjZQNm5aMm41akhlUEFZWlVuc2U2c24zaUUyWFhZcDdIYUJ3Ukt2aFFLOGwxMDUydk5JTjdDVHhxOVdnRlNaUWJzNFhBcVg2elNMZXpIcmsyRGo0RW0zUFZ4b0E1WjdyWDRUaXY2TFlNZk5CN0tURmIxUTFYZWRmdmt1cl94QTAzbVktSm1BTnFj?oc=5"
    },
    {
        "id": 20,
        "category": "local",
        "title": "전남 학교에 ‘AI 사용 기준’ 떴다…교사·학생 필수 가이드 배포",
        "date": "2026.02.12",
        "oneLine": "전남 학교에 ‘AI 사용 기준’ 떴다…교사·학생 필수 가이드 배포",
        "content": "전남 학교에 ‘AI 사용 기준’ 떴다…교사·학생 필수 가이드 배포  나주신문",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "기획/개발 팀은 해당 뉴스에 언급된 기술적 기능(기능명, UX 동선 등)을 벤치마킹하여 차기 업데이트 로드맵에 반영하십시오. 특히 사용자 경험(UX) 측면에서 교사의 업무 경감을 돕는 자동화 기능이 강조되고 있음에 주목해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiakFVX3lxTE1kMTAyWWkzbE85VVVuaU9XNlUxTXg3bHNmeHJzbnhkUGgzbWV6ZjM3TFhZMDVwTlFyQndYM0d0NkdlS1pkWElRZDBTTzQ5U3dEX0Q2XzMxSzZaRUN2ODg4Zk9uZXl5OGxnVFHSAWxBVV95cUxQWks5S25XcHNMX1lRM0lBRHZObjQyNXBGRTFyMkY3U18za19Ba2F1a05hU282RjJoOGxsaXFaRU81aS1MeTFjTkdXUmYxdHV5bXluN0NVY1YwbS1kaHphZjFGV2k2TjdnTHRFY3Q?oc=5"
    },
    {
        "id": 21,
        "category": "iscream",
        "title": "서울특별시교육청·버블콘, BETT UK서 AI 기반 공교육 혁신 모델 제시",
        "date": "2026.02.12",
        "oneLine": "서울특별시교육청·버블콘, BETT UK서 AI 기반 공교육 혁신 모델 제시",
        "content": "서울특별시교육청·버블콘, BETT UK서 AI 기반 공교육 혁신 모델 제시  MSN",
        "importance": "글로벌 빅테크 기업들의 교육 시장 진출 가속화와 맥락을 같이 하는 뉴스입니다. 이는 단기적으로는 경쟁 심화를 의미하지만, 장기적으로는 AI 기반 맞춤형 학습 시장의 전체 파이(Total Addressable Market)가 커지고 있음을 시사하므로 적극적인 투자가 필요합니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiiANBVV95cUxNaUR4WG0zeXNVX3BQNmFycDEyM3Nkb2ZibUlCdk00NmthTzEyUVI0cnZqSl9NSFFCTWZCRXlkUjdfeHJ3SGlzWHZ0d3UyWWF5a0JLa0pocUhVZ0VnZHEtRUE2QjItRkdQWkpfTzM0ajJ1R1BCUDBVZk9FS3BSMEh3NXRIU1BORXZpZXlwVndUOXFoQmFZM0RFMG5pLVZYQldiV08taER0N0FRVHR4ZkdlZWNGdWh2NU8wcFdqNzdHVDlnYlFNU3VDQ3c2OGJSMWtrdUp4RU1PYklDSVU0QVNmMW80bDM3ZF9yeTFuOVpFZ2t5R3V2Qld5UTJuSWtqS0Myei11WDh2b1lydUgzdjNWOEdraFJMMWQ0eDBqbVdGVElINlNNaGNVVHRkamlFOEhQc1NkRVpMdmtWZURJUHdnUE5NWEJqOC1mV2tqcmJMV0poV3VheTR5dkpIcDZFSlpmVUJvREVTSFFHdHJOeGd5eE1wUzBzRDR5emJFbGJHSHlEZUxQRWxPUw?oc=5"
    },
    {
        "id": 22,
        "category": "iscream",
        "title": "[KFE 유통로그]교원 플래너스어학원·아이스크림미디어 하이클래스, 신학기 수요 겨냥",
        "date": "2026.02.12",
        "oneLine": "[KFE 유통로그]교원 플래너스어학원·아이스크림미디어 하이클래스, 신학기 수요 겨냥",
        "content": "[KFE 유통로그]교원 플래너스어학원·아이스크림미디어 하이클래스, 신학기 수요 겨냥  한국금융경제신문",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMibEFVX3lxTFBQMjY0aVZ3MGx2MlFmN0hMckZJb0lCV010eWFZdXNJbjlud1FHN0pxaHNURnoxLWlrM1JXRFNGUXhsOWpBQ2drQ0lydm9GVnlXTXgyUkx5RUNHVFR2ZWRLYjdSNkNwT0p3aDRqSdIBcEFVX3lxTFBDa2UxQnNoVnkyR3pLNGlyaGlLcUFNdnhmNjJCZmZpelRMQ2Y4VmtTQk5wRFV2bGtuQ2dxbFlEZjNpMjAwbV9QLVBrUGEwNERnXzlEWlFRRHVQV0VWZ1dZeVpyR2V2Y1VyVHc0TUotTjI?oc=5"
    },
    {
        "id": 23,
        "category": "policy",
        "title": "김상권 경남교육감 예비후보, 학력분야 1호 공약 발표",
        "date": "2026.02.12",
        "oneLine": "김상권 경남교육감 예비후보, 학력분야 1호 공약 발표",
        "content": "김상권 경남교육감 예비후보, 학력분야 1호 공약 발표  매일일보",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiY0FVX3lxTE00YVNQREx0Z0NKRE1Sa2hqY2VMUHVyRW94LXJoZXFTdHNRR19Ca3NhRUMxZ2hiN0tpdzlVNElHNWdMSzFZRVJ2eHJzd3ZOcmhHa01KdFgyV3dsQzFZMTlkbUx2OA?oc=5"
    },
    {
        "id": 24,
        "category": "local",
        "title": "경기교육청, 영어교육 격차 줄인다…취약계층 맞춤 지원 확대",
        "date": "2026.02.12",
        "oneLine": "경기교육청, 영어교육 격차 줄인다…취약계층 맞춤 지원 확대",
        "content": "경기교육청, 영어교육 격차 줄인다…취약계층 맞춤 지원 확대  KPI뉴스",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMiXEFVX3lxTFBGY3R1SktUa1l3c0JvdU1PYW8ta1Bxa2xQV3h5REVMalkzNjJEWXBSTWRKUnlRWEsyYU5SS2RhWk1ReXpxaEtiZlNvNDFtYldlOHQyNFdtd1l4RHlL0gFTQVVfeXFMTU5TUzlVTVRUUXJqMTN2cHBLZzlkTlY5SDMxQWpuc0lvVG9jLVJBTWFkVy1Sekg1S0VrWHVLNmVpbTlIMDJpVUd0V0J6NEFWbVY1UWc?oc=5"
    },
    {
        "id": 25,
        "category": "policy",
        "title": "청주대, 9년 연속 ‘교육국제화역량 인증’",
        "date": "2026.02.12",
        "oneLine": "청주대, 9년 연속 ‘교육국제화역량 인증’",
        "content": "청주대, 9년 연속 ‘교육국제화역량 인증’  대학저널",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE1MQUxuM0pzeFZUb1VQR0dVRkp1bmhieDNjWGdNLW5DSVdXVEx0dERXWmduLW5PUmRtcWIzZlpVVk1yT1BhWW4tY0VBTkdLbWZmZ1VJSVhKb0JZbU3SAWpBVV95cUxPS1FoTzFtSFJ2N1VHOEh1d19fYlVVZ0NqNkk4NzNLS01fbUR4ZWpJU1RyZTBzcWFNN3h3NGdFSUxkSGZJQWFoUUhBcjZRaXFwN05lcEdEWUl3UjBYc3B2cHVZcVpRVUpDcEdn?oc=5"
    },
    {
        "id": 26,
        "category": "local",
        "title": "광주광역시교육청, '2026년도 중증장애인 교육공무직원 채용시험' 공고",
        "date": "2026.02.12",
        "oneLine": "광주광역시교육청, '2026년도 중증장애인 교육공무직원 채용시험' 공고",
        "content": "광주광역시교육청, '2026년도 중증장애인 교육공무직원 채용시험' 공고  에이블뉴스",
        "importance": "정부 규제 및 표준화 움직임과 관련이 깊습니다. 특히 최근 강조되고 있는 'AI 디지털 교과서'의 법적 기준이나 윤리적 가이드라인 준수 여부가 쟁점이 될 수 있으므로, 선제적인 컴플라이언스 점검과 대관 업무 강화가 요구되는 시점입니다.",
        "insight": "영업 및 현장 지원 부서에서는 일선 학교 방문 시 이 이슈를 스몰토크 주제로 활용하여 교사들의 실제 반응을 수집하십시오. 현장의 목소리가 제품 개선으로 이어지는 선순환 구조를 만들기 위해, 수집된 피드백을 주간 회의에서 반드시 공유해야 합니다.",
        "url": "https://news.google.com/rss/articles/CBMickFVX3lxTE9idWNUTV9SMXNOT0NpUXNLbXhfS2RreVBXcUx1eC1UaGVTc09HODM4WlpvQjFHQUtvUkFHUmVnQXNWSHlNVDQtcVlWWjRZWEd3UXFfZ3llSFFUVUxfal9RaEk0MlFWZGJzSUZjZnhYVUFmUdIBckFVX3lxTE9idWNUTV9SMXNOT0NpUXNLbXhfS2RreVBXcUx1eC1UaGVTc09HODM4WlpvQjFHQUtvUkFHUmVnQXNWSHlNVDQtcVlWWjRZWEd3UXFfZ3llSFFUVUxfal9RaEk0MlFWZGJzSUZjZnhYVUFmUQ?oc=5"
    },
    {
        "id": 27,
        "category": "iscream",
        "title": "윌비스, +4.92% 상승폭 확대",
        "date": "2026.02.12",
        "oneLine": "윌비스, +4.92% 상승폭 확대",
        "content": "윌비스, +4.92% 상승폭 확대 - 조선비즈  Chosunbiz",
        "importance": "최근 교육 현장에서의 요구 사항이 반영된 뉴스로, 향후 플랫폼 고도화 방향 설정에 있어 중요한 참고 지표가 될 것입니다. 단순한 기능 제공을 넘어 교사와 학생의 실질적인 페인 포인트(Pain Point)를 해결해 줄 수 있는 솔루션으로서의 가치를 증명해야 하는 시점입니다.",
        "insight": "마케팅 팀은 본 기사의 핵심 키워드를 활용하여 아이스크림미디어의 브랜드 메시지를 다듬어야 합니다. '선생님을 위한 AI', '안전한 에듀테크' 등의 키워드와 연계하여 자사 서비스의 신뢰도를 높이는 콘텐츠(카드뉴스, 아티클) 발행을 검토해 보시기 바랍니다.",
        "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxQMmFTN3htV01WWmNuTnZRa2M3NWltT2RxR0cxT3kwc1pCRWsxNFBJR2QyNG5lNEtEMEhXTV9zakNJZzA2ZmNYODFwSnIzTHBhU3h6Wi16cDd1dzIwajBreWlKaFZ1S1Vxa292X21XazFYaXRra1FDVjNMb3NmVjZ3eThMVlNSQVNOZFZqTTNmeXdGRl9nSWpF0gGXAUFVX3lxTFAyYVM3eG1XTVZaY25OdlFrYzc1aW1PZHFHRzFPeTBzWkJFazE0UElHZDI0bmU0S0QwSFdNX3NqQ0lnMDZmY1g4MXBKcjNMcGFTeHpaLXpwN3V3MjBqMGt5aUpoVnVLVXFrb3ZfbVdrMVhpdGtrUUNWM0xvc2ZWNnd5OExWU1JBU05kVmpNM2Z5d0ZGX2dJakU?oc=5"
    }
];